### ISSUE TITLE
can i have your pretrained dataset of checkpoints

### ISSUE THREAD

**Issue by sorobedio** [SamsungSAILMontreal/nino#1]
Hello,
thank you for the great job.
can i have the dataset of checkpoints ?
thank you

**Comment by bknyaz** [comment]
Hi, I should be able to put it online this week. It will be around 200gb.

**Comment by bknyaz** [comment]
We uploaded the dataset here https://huggingface.co/datasets/SamsungSAILMontreal/nino_metatrain/.

See an example here:
https://huggingface.co/datasets/SamsungSAILMontreal/nino_metatrain/blob/main/README.md#example

We are planning to put more examples and code to train NiNo next week.

**Comment by Dunc4nJ** [comment]
Would definitely be interested in seeing the NiNo train code as well. Thank you for your efforts!

**Comment by bknyaz** [comment]
see #2 , we just released the training code
