### ISSUE TITLE
Question about the strikes in Nino predictions

### ISSUE THREAD

**Issue by gw103** [SamsungSAILMontreal/nino#3]
Dear authors, I'm really interested and impressed in your work of training a model to help model learn. However, I'm also a bit confused about the result. 
After every 1000 steps, the Nino will predict once, however, the loss after the prediction went up, yet in general it does speed up the training. I would really appreciate it if you could provide some explanations on this.
<img width="354" alt="截屏2024-11-05 14 11 57" src="https://github.com/user-attachments/assets/946da5cf-6b69-44db-96f1-79b88bba9b22">

**Comment by bknyaz** [comment]
Thank you! When NiNo makes predictions, most of the parameters are generally predicted in the right direction however some parameters may be predicted inaccurately. For the loss spike it can be enough to have just one parameter to be predicted way off. However, a few training iterations can easily correct those wrong parameter values. So NiNo makes a good global-level prediction while Adam can fix any local-level mistakes.
Let me know if you have further questions.

**Comment by gw103** [comment]
Thanks Dr. Knyazev, it makes sense!

**Comment by CornerstoneHUBinPUT** [comment]
you're good but you're still wonderful architect
