### ISSUE TITLE
Do you know how to download a subset of your dataset?

### ISSUE THREAD

**Issue by gw103** [SamsungSAILMontreal/nino#4]

**Comment by bknyaz** [comment]
you should be able to download individual parquet files from https://huggingface.co/datasets/SamsungSAILMontreal/nino_metatrain/tree/main
or try dataset = load_dataset('SamsungSAILMontreal/nino_metatrain', 'fm-16', streaming=True). But I haven't tested that. But using mmap is preferable as it's much faster to read it during training.
